# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --if-present
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: site_content
        path: ./dist

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
    - name: List Goodies
      run: ls -l
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.PUBLISH_AWS_KEY }}
        aws-secret-access-key: ${{ secrets.PUBLISH_AWS_SECRET }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./site_content s3://infightio --delete # --acl public-read
    - name: Invalidate Cloudfront
      run: aws cloudfront create-invalidation --distribution-id E22U5KUL7BEIEK --paths "/*"